# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 15:14
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0002_auto_20170423_1513'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventperson',
            name='action_network_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='city',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='state',
            field=localflavor.us.models.USPostalCodeField(blank=True, default='PA', max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='street_address_one',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='street_address_two',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='zip_code',
            field=localflavor.us.models.USZipCodeField(blank=True, max_length=10, null=True),
        ),
    ]
