# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-23 19:39
from __future__ import unicode_literals

from django.db import migrations, models
import localflavor.us.models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_auto_20170423_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventperson',
            name='action_network_id',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='city',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='phone_number',
            field=localflavor.us.models.PhoneNumberField(blank=True, default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='street_address_one',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='eventperson',
            name='street_address_two',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
